function value = lab_strategy
    value = ["Manual", "Random", "weight-based Random", "Greedy", "weight-based Greedy", "Proportion", ...
    "ProportionPro", "ProportionNB", "ProportionNBPro", "Ladder", "FastLadder", "LadderPro", "FastLadderPro", ...
    "weight-based LP", "weight-based FLP", "Hybrid", "FastHybrid", "TG", "proportion-based Random", "MWAoI", "WIP"];
end